### ISSUE TITLE
📃 Readme 초안을 작성해요

### ISSUE THREAD

**Issue by BaeJunH0** [BaeJunH0/AlumniLink_BE#30]
### 구현 사항

- 리드미 작성

### 구현 이유

- 프로젝트 기능과 개발 주안점을 드러내기 위해서

**Comment by Sunja-An** [comment]
기능 부분 추가 건의 사항
1. 졸업생 -> 어디 계열 졸업생인지 표기하는 부분 있었으면 좋겠음.
2. 졸업한 걸 인증하는 과정도 있으면 좋겠지만,, 너무 무거워지면 안해도 될듯
3. 추천기능 추가 어떤지
